version: 1.3.0-{branch}-{build}
image: WMF 5
init:
- ps: 
environment:
  LDLOADLIBS: -lstdc++
  SLIC3R_STATIC: 1
  SLIC3R_VERSION: 1.3.0
  BOOST_DIR: C:\dev\boost_1_63_0
  WXDIR: C:\dev\wxwidgets
  WXSHARED: SHARED=0
  FORCE_WX_BUILD: 0
  FORCE_BOOST_REINSTALL: 0
  ENC_SECRET:
    secure: QfeTOSKXz1uFCEACqFKLNw==
  UPLOAD_USER:
    secure: fYPwnI3p6HNR+eMRJR3JfmyNolFn+Uc0MUn2bBXp9uU=
  matrix:
    - ARCH: 64bit
    - ARCH: 32bit

install:
  - IF DEFINED ENC_SECRET nuget install secure-file -ExcludeVersion
  - IF DEFINED ENC_SECRET secure-file\tools\secure-file -decrypt package/deploy/slic3r-upload.ppk.enc -secret %ENC_SECRET%
  - ps: "& package/win/appveyor_preinstall.ps1"
cache:
- C:\Users\appveyor\local-lib-64bit.7z
- C:\Users\appveyor\local-lib-32bit.7z
- C:\Users\appveyor\freeglut.64bit.7z
- C:\Users\appveyor\freeglut.32bit.7z
- C:\users\appveyor\strawberry.64bit.msi
- C:\users\appveyor\strawberry.32bit.msi
- C:\Users\appveyor\winscp.zip
- C:\Users\appveyor\extra_perl.7z
- C:\Users\appveyor\wxwidgets-64bit.7z
- C:\Users\appveyor\wxwidgets-32bit.7z
- C:\Users\appveyor\boost.1.63.0.32bit.7z
- C:\Users\appveyor\boost.1.63.0.64bit.7z
build_script:
- ps: "& package/win/appveyor_buildscript.ps1"
artifacts:
- path: .\slic3r*zip
  name: slic3r-dev
deploy_script:
- ps:  "cd C:/projects/slic3r; & package/win/appveyor_deploy.ps1"
on_success:
- ps: 
on_failure:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
- ps:
