version: 1.3.0-{branch}-{build}
image: WMF 5
init:
- ps: 
environment:
  LDLOADLIBS: -lstdc++
  SLIC3R_STATIC: 1
  SLIC3R_VERSION: 1.3.0
  BOOST_DIR: C:\dev\boost_1_63_0
  WXSHARED: SHARED=0
  FORCE_WX_BUILD: 0
  FORCE_BOOST_REINSTALL: 0
  ENC_SECRET:
    secure: QfeTOSKXz1uFCEACqFKLNw==
  UPLOAD_USER:
    secure: fYPwnI3p6HNR+eMRJR3JfmyNolFn+Uc0MUn2bBXp9uU=

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt package/deploy/slic3r-upload.ppk.enc -secret %ENC_SECRET%
  - ps: "& package/win/appveyor_preinstall.ps1"
cache:
- C:\Users\appveyor\boost.1.63.0.7z
- C:\Users\appveyor\local-lib.7z
- C:\Strawberry\perl\site
- C:\Users\appveyor\freeglut.7z
- C:\users\appveyor\strawberry.msi
- C:\Users\appveyor\winscp.zip
- C:\Users\appveyor\extra_perl.7z
- C:\Users\appveyor\wxwidgets.7z
build_script:
- ps: "& package/win/appveyor_buildscript.ps1"
test_script:
- ps: "mkdir C:\\Andrés\nwget \"http://www.thingiverse.com/download:73351\" -o\"C:\\Andrés\\5mm.stl\"\necho \"bed_temperature=60\" > C:\\Andrés\\test.ini\n\ncd C:\\projects\\slic3r\nperl slic3r.pl --load \"C:\\Andrés\\test.ini\" \"C:\\Andrés\\5mm.stl\"\n\nif (!(Test-Path  \"C:\\Andrés\\5mm.gcode\")) {\necho \"IS IT HERE\"\n}"
artifacts:
- path: .\slic3r*zip
  name: slic3r-dev
deploy_script:
- ps:  "& package/win/appveyor_deploy.ps1"
on_success:
- ps: 
on_failure:
- ps: 
on_finish:
- ps:
