name: C/C++ Nigthly macos

on:
  push:
    branches:
      - Nigthly

jobs:
  build:

    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'Nigthly'
    - name: build deps & slicer
      run: ./BuildMacOS.sh -i
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.tar
        path: build/Slic3r.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nightly_macos.dmg
        path: build/Slic3r.dmg
